### ISSUE TITLE
error while joining a chan

### ISSUE THREAD

**Issue by ahyear** [ircanywhere/ircanywhere#251]
I get this error while I access a new chan ( one that was not yet open ):

Recieved unknown RPC event: error Object {command: "selectTab", error: "invalid document properties, see API docs"}
sockets.js:214 

Thanks again!

**Comment by rickihastings** [comment]
I can't replicate this, opening new channels for me works fine? Have you any more info to replicate

**Comment by ahyear** [comment]
since the last update ( the one from le 15th jan ) i don't have this problem anymore.
thank you
