### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by kxra** [ircanywhere/ircanywhere#259]
http://try.ircanywhere.com/

"IRCAnywhere
Hang tight, we're loading everything for you..."

**Comment by zamabe** [comment]
```
try.ircanywhere.com  /templates.js:     404
try.ircanywhere.com  /ircanywhere.css:  404
```

**Comment by zamabe** [comment]
This is still the case

**Comment by Cydrobolt** [comment]
Still happening.

**Comment by dbkaplun** [comment]
+1

**Comment by MarkCole** [comment]
Hey all.  Thanks for the issue report.  The try server was misconfigured and eventually shut down.  This link will be removed from the site until if ever a new demo is put up.  This was just a demo install, you are recommended to install it on your own server if you want to use the software.

**Comment by kxra** [comment]
i still see the link on the site but it still doesn't work

**Comment by zamabe** [comment]
https://github.com/ircanywhere/ircanywhere.github.io/pull/5
